### ISSUE TITLE
gamedata/tf2.attributes.txt is no longer correct

### ISSUE THREAD

**Issue by joeyjumper94** [nosoop/tf2attributes#6] opened 2021-07-22 01:46 UTC
the latest update to TF2 seems to have broken this plugin again

**Comment by nosoop** [comment] 2021-07-22 04:21
Could you clarify what isn't working &mdash; any error messages or functions that have unexpected behavior?

**Comment by joeyjumper94** [comment] 2021-07-22 08:44
it says "Could not initialize call to CEconItemSchema::GetItemDefinition"

**Comment by nosoop** [comment] 2021-07-24 12:07
Hmm, looks fine to me &mdash; just booted up my dedicated Windows instance and I don't see any difference in the signature.  The signature's still valid after checking the disassembly.

Please make sure you've installed the gamedata correctly (and that it's the same one from this repository), and that you've restarted the server after doing so &mdash; you may be seeing the same issue as nosoop/SM-TFEconData#8 where the error reported is caused by a different problem.

**Comment by nosoop** [comment] 2021-08-03 04:04
Going to go ahead and close this since it doesn't seem like an issue with the gamedata itself; please retest and make sure you that you did install the updated gamedata and have restarted your server.

**Closed as completed by nosoop** 2021-08-03 04:04 UTC
Labels: invalid
